//! Editor screens.

pub mod choice_modal;
pub mod color_menu;
pub mod confirm_modal;
pub mod diagnostics;
pub mod import_export_menu;
pub mod info_modal;
pub mod items_editor;
pub mod line_list_editor;
pub mod main_menu;
pub mod placeholder;
pub mod powerline_setup;
pub mod terminal_options;
pub mod text_edit_modal;
pub mod update_checker_menu;
pub mod widget_editor;
pub mod widget_picker;
pub mod wizard;

pub use choice_modal::ChoiceModal;
pub use color_menu::ColorMenu;
pub use confirm_modal::ConfirmModal;
pub use diagnostics::DiagnosticsScreen;
pub use import_export_menu::ImportExportMenu;
pub use info_modal::InfoModal;
pub use items_editor::ItemsEditor;
pub use line_list_editor::LineListEditor;
pub use main_menu::MainMenu;
pub use placeholder::Placeholder;
pub use powerline_setup::PowerlineSetup;
pub use terminal_options::TerminalOptionsMenu;
pub use text_edit_modal::TextEditModal;
pub use update_checker_menu::UpdateCheckerMenu;
pub use widget_editor::WidgetEditor;
pub use widget_picker::WidgetPicker;
pub use wizard::wizard_entry;
